version: '3'
services:
  web:
    build: .
    ports:
    - 3000
    environment:
      - VIRTUAL_HOST=ratemyapartment.fahad.alhatshami.se
      - LETSENCRYPT_HOST=ratemyapartment.fahad.alhatshami.se
      - DATABASE_URL=${DATABASE_URL}
  db:
    image: postgres:14-alpine
    restart: always
    ports:
      - 5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./postgres-dataa:/var/lib/postgresql/data
          # copy the sql script to create tables
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
volumes:
  postgres_data:
  postgres_config:





